const character = [
  {
    name: 'Codyman',
    characterExp: 0,
    currentLevelExp: 0,
    currentLevel: 1,
    coins: 0,
    chestExp: 0,
    chestCurrentLevelExp: 0,
    chestCurrentLevel: 1,
    backExp: 0,
    backCurrentLevelExp: 0,
    backCurrentLevel: 1,
    armsExp: 0,
    armsCurrentLevelExp: 0,
    armsCurrentLevel: 1,
    abdominalsExp: 0,
    abdominalsCurrentLevelExp: 0,
    abdominalsCurrentLevel: 1,
    legsExp: 0,
    legsCurrentLevelExp: 0,
    legsCurrentLevel: 1,
    shouldersExp: 0,
    shouldersCurrentLevelExp: 0,
    shouldersCurrentLevel: 1,
    cardioExp: 0,
    cardioCurrentLevelExp: 0,
    cardioCurrentLevel: 1,
    stretchingExp: 0,
    stretchingCurrentLevelExp: 0,
    stretchingCurrentLevel: 1,
    weapon: null,
    head: null,
    chest: null,
    leg: null,
    ring: null,
    image: 'https://png.pngtree.com/png-vector/20201228/ourmid/pngtree-a-warrior-boy-clipart-png-image_2659449.jpg'
  },
  {
    name: 'Murphy the Legend',
  },
]

module.exports = character
